name: 'Setup Fortify ScanCentral Client'
description: 'Setup Fortify ScanCentral Client'
author: 'Ruud Senden'
inputs:
  version:
    description: 'Fortify ScanCentral Client version to use'
    required: true
    default: 20.1.0
runs:
  using: 'node12'
  main: 'index.js'